<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>com.github.sanchezavr123-lgtm.DotaPeak</AssemblyName>
    <AssemblyTitle>Dota x PEAK</AssemblyTitle>
    <Version>1.1.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
